version: "3.1"
volumes:
  shop-assistance-volume1:
    
services:
  mongodb:
    image: mongo
    container_name: shop-mongodb
    restart: "no"
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-seed:/mongo-seed
      - ./mongo-seed/mongo_import.sh:/docker-entrypoint-initdb.d/001-mongo_import.sh
      - shop-assistance-volume1:/data/db
