volumes:
  shop-assistance-volume:

version: '3'

services:
  mongo:
    image: mongo:3.6
    container_name: 'shop-assistance-mongo-container'
    restart: 'no'
    environment:
     - MONGO_INITDB_DATABASE=shop-assistance
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
     - '27018:27017'   
    volumes: 
     - shop-assistance-volume:/data/db
