version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: "no"
     ports:
      - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somepass
       MYSQL_DATABASE: db_name
       MYSQL_USER: user
       MYSQL_PASSWORD: pass

volumes:
    db_data: {}
